<!-- Статика -->
<div style="position:absolute;left:41px;top:48px;width:871px;height:812px;z-index:0;"><img src="/ASUTP/img/cshi_pfu5/main.png" alt=""></div>
<div style="position:absolute;left:930px;top:52px;width:258px;height:436px;z-index:0;"><img src="/ASUTP/img/cshi_pfu5/menu.png" alt=""></div>
<div style="position:absolute;left:524px;top:709px;width:17px;height:17px;z-index:45;"><img src="/ASUTP/img/cshi_pfu5/img0004.png" alt=""></div>
<div style="position:absolute;left:610px;top:709px;width:17px;height:17px;z-index:46;"><img src="/ASUTP/img/cshi_pfu5/img0004.png" alt=""></div>
<!-- Текст -->
<div id="pfu5_d4" class="mode_UnCertain" style="position:absolute;left:292px;top:185px;width:42px;height:15px;text-align:center;z-index:2;"><span style="color:#000000;font-family:Arial;font-size:12px;"><strong id="pfu5_d4_text">Р/А</strong></span></div>
<div id="pfu5_d11" class="mode_UnCertain" style="position:absolute;left:508px;top:185px;width:42px;height:15px;text-align:center;z-index:3;"><span style="color:#000000;font-family:Arial;font-size:12px;"><strong id="pfu5_d11_text">Р/А</strong></span></div>
<div id="pfu5_d18" class="mode_UnCertain" style="position:absolute;left:711px;top:185px;width:42px;height:15px;text-align:center;z-index:4;"><span style="color:#000000;font-family:Arial;font-size:12px;"><strong id="pfu5_d18_text">Р/А</strong></span></div>
<div id="pfu5_d25" class="mode_UnCertain" style="position:absolute;left:861px;top:185px;width:42px;height:15px;text-align:center;z-index:5;"><span style="color:#000000;font-family:Arial;font-size:12px;"><strong id="pfu5_d25_text">Р/А</strong></span></div>
<div id="pfu5_d32" class="mode_UnCertain" style="position:absolute;left:176px;top:227px;width:42px;height:15px;text-align:center;z-index:1;"><span style="color:#000000;font-family:Arial;font-size:12px;"><strong id="pfu5_d32_text">Р/А</strong></span></div>
<div id="pfu5_d48" class="mode_UnCertain" style="position:absolute;left:153px;top:575px;width:42px;height:15px;text-align:center;z-index:36;"><span style="color:#000000;font-family:Arial;font-size:12px;"><strong id="pfu5_d48_text">Р/А</strong></span></div>
<div id="pfu5_d37" class="mode_UnCertain" style="position:absolute;left:451px;top:447px;width:42px;height:15px;text-align:center;z-index:37;"><span style="color:#000000;font-family:Arial;font-size:12px;"><strong id="pfu5_d37_text">Р/А</strong></span></div>
<div id="pfu5_d46" class="mode_UnCertain" style="position:absolute;left:478px;top:709px;width:42px;height:15px;text-align:center;z-index:38;"><span style="color:#000000;font-family:Arial;font-size:12px;"><strong id="pfu5_d46_text">Р/А</strong></span></div>
<div id="pfu5_d1" class="rdy_UnCertain" style="position:absolute;left:292px;top:223px;width:111px;height:15px;text-align:center;z-index:10;"><span style="color:#000000;font-family:Arial;font-size:12px;"><strong id="pfu5_d1_text">-</strong></span></div>
<div id="pfu5_d8" class="rdy_UnCertain" style="position:absolute;left:439px;top:223px;width:111px;height:15px;text-align:center;z-index:14;"><span style="color:#000000;font-family:Arial;font-size:12px;"><strong id="pfu5_d8_text">-</strong></span></div>
<div id="pfu5_d15" class="rdy_UnCertain" style="position:absolute;left:642px;top:223px;width:111px;height:15px;text-align:center;z-index:18;"><span style="color:#000000;font-family:Arial;font-size:12px;"><strong id="pfu5_d15_text">-</strong></span></div>
<div id="pfu5_d22" class="rdy_UnCertain" style="position:absolute;left:792px;top:223px;width:111px;height:15px;text-align:center;z-index:22;"><span style="color:#000000;font-family:Arial;font-size:12px;"><strong id="pfu5_d22_text">-</strong></span></div>
<div id="pfu5_d29" class="rdy_UnCertain" style="position:absolute;left:107px;top:265px;width:111px;height:15px;text-align:center;z-index:6;"><span style="color:#000000;font-family:Arial;font-size:12px;"><strong id="pfu5_d29_text">-</strong></span></div>
<div id="pfu5_scales_state_1" class="load_UnCertain" style="position:absolute;left:292px;top:239px;width:111px;height:15px;text-align:center;z-index:11;"><span style="color:#000000;font-family:Arial;font-size:12px;"><strong id="pfu5_scales_state_1_text" >-</strong></span></div>
<div id="pfu5_scales_state_2" class="load_UnCertain" style="position:absolute;left:439px;top:239px;width:111px;height:15px;text-align:center;z-index:15;"><span style="color:#000000;font-family:Arial;font-size:12px;"><strong id="pfu5_scales_state_2_text" >-</strong></span></div>
<div id="pfu5_scales_state_3" class="load_UnCertain" style="position:absolute;left:642px;top:239px;width:111px;height:15px;text-align:center;z-index:19;"><span style="color:#000000;font-family:Arial;font-size:12px;"><strong id="pfu5_scales_state_3_text" >-</strong></span></div>
<div id="pfu5_scales_state_4" class="load_UnCertain" style="position:absolute;left:792px;top:239px;width:111px;height:15px;text-align:center;z-index:23;"><span style="color:#000000;font-family:Arial;font-size:12px;"><strong id="pfu5_scales_state_4_text">-</strong></span></div>
<div id="pfu5_scales_state_5" class="load_UnCertain" style="position:absolute;left:107px;top:281px;width:111px;height:15px;text-align:center;z-index:7;"><span style="color:#000000;font-family:Arial;font-size:12px;"><strong id="pfu5_scales_state_5_text">-</strong></span></div>
<div style="position:absolute;left:297px;top:259px;width:87px;height:22px;text-align:center;z-index:12;"><span style="color:#0000FF;font-family:Arial;font-size:19px;"><strong id="pfu5_ma2" class="analog">- кг</strong></span></div>
<div style="position:absolute;left:297px;top:297px;width:87px;height:22px;text-align:center;z-index:13;"><span style="color:#0000FF;font-family:Arial;font-size:19px;"><strong id="pfu5_ma1" class="analog">- кг</strong></span></div>
<div style="position:absolute;left:444px;top:259px;width:87px;height:22px;text-align:center;z-index:16;"><span style="color:#0000FF;font-family:Arial;font-size:19px;"><strong id="pfu5_ma22" class="analog">- кг</strong></span></div>
<div style="position:absolute;left:444px;top:297px;width:87px;height:22px;text-align:center;z-index:17;"><span style="color:#0000FF;font-family:Arial;font-size:19px;"><strong id="pfu5_ma21" class="analog">- кг</strong></span></div>
<div style="position:absolute;left:647px;top:259px;width:87px;height:22px;text-align:center;z-index:20;"><span style="color:#0000FF;font-family:Arial;font-size:19px;"><strong id="pfu5_ma42" class="analog">- кг</strong></span></div>
<div style="position:absolute;left:647px;top:297px;width:87px;height:22px;text-align:center;z-index:21;"><span style="color:#0000FF;font-family:Arial;font-size:19px;"><strong id="pfu5_ma41" class="analog">- кг</strong></span></div>
<div style="position:absolute;left:797px;top:259px;width:87px;height:22px;text-align:center;z-index:24;"><span style="color:#0000FF;font-family:Arial;font-size:19px;"><strong id="pfu5_ma62" class="analog">- кг</strong></span></div>
<div style="position:absolute;left:797px;top:297px;width:87px;height:22px;text-align:center;z-index:25;"><span style="color:#0000FF;font-family:Arial;font-size:19px;"><strong id="pfu5_ma61" class="analog">- кг</strong></span></div>
<div style="position:absolute;left:112px;top:301px;width:87px;height:22px;text-align:center;z-index:8;"><span style="color:#0000FF;font-family:Arial;font-size:19px;"><strong id="pfu5_ma82" class="analog">- кг</strong></span></div>
<div style="position:absolute;left:112px;top:339px;width:87px;height:22px;text-align:center;z-index:9;"><span style="color:#0000FF;font-family:Arial;font-size:19px;"><strong id="pfu5_ma81" class="analog">- кг</strong></span></div>
<div style="position:absolute;left:823px;top:468px;width:87px;height:22px;text-align:center;z-index:26;"><span style="color:#0000FF;font-family:Arial;font-size:19px;"><strong id="pfu5_a3" class="analog">- А</strong></span></div>
<div style="position:absolute;left:823px;top:492px;width:87px;height:22px;text-align:center;z-index:27;"><span style="color:#0000FF;font-family:Arial;font-size:19px;"><strong id="pfu5_a4" class="analog">- А</strong></span></div>
<div id="pfu5_d36" class="glamp_UnCertain" style="position:absolute;left:632px;top:420px;width:277px;height:19px;text-align:center;z-index:28;"><span style="color:#000000;font-family:Arial;font-size:17px;"><strong>Готовность к загрузке</strong></span></div>
<div id="pfu5_d42" class="rlamp_UnCertain" style="position:absolute;left:632px;top:444px;width:277px;height:19px;text-align:center;z-index:29;"><span style="color:#000000;font-family:Arial;font-size:17px;"><strong>Авария</strong></span></div>
<div id="pfu5_d54" class="rlamp_UnCertain" style="position:absolute;left:632px;top:565px;width:277px;height:19px;text-align:center;z-index:30;"><span style="color:#000000;font-family:Arial;font-size:17px;"><strong>Сход ленты влево</strong></span></div>
<div id="pfu5_d55" class="rlamp_UnCertain" style="position:absolute;left:632px;top:589px;width:277px;height:19px;text-align:center;z-index:31;"><span style="color:#000000;font-family:Arial;font-size:17px;"><strong>Сход ленты вправо</strong></span></div>
<div id="pfu5_d56" class="rlamp_UnCertain" style="position:absolute;left:632px;top:615px;width:277px;height:19px;text-align:center;z-index:32;"><span style="color:#000000;font-family:Arial;font-size:17px;"><strong>Аварийный останов слева</strong></span></div>
<div id="pfu5_d57" class="rlamp_UnCertain" style="position:absolute;left:632px;top:639px;width:277px;height:19px;text-align:center;z-index:33;"><span style="color:#000000;font-family:Arial;font-size:17px;"><strong>Аварийный останов справа</strong></span></div>
<div id="pfu5_d58" class="rlamp_UnCertain" style="position:absolute;left:632px;top:663px;width:277px;height:19px;text-align:center;z-index:34;"><span style="color:#000000;font-family:Arial;font-size:17px;"><strong>Датчик скорости</strong></span></div>
<div id="pfu5_d59" class="rlamp_UnCertain" style="position:absolute;left:632px;top:688px;width:277px;height:19px;text-align:center;z-index:35;"><span style="color:#000000;font-family:Arial;font-size:17px;"><strong>Кнопка аварийного останова</strong></span></div>
<div id="pfu5_d60" class="rlamp_UnCertain" style="position:absolute;left:51px;top:649px;width:158px;height:19px;text-align:center;z-index:41;"><span style="color:#000000;font-family:Arial;font-size:17px;"><strong>Авария</strong></span></div>
<div id="alarm1" class="rlamp_UnCertain" style="position:absolute;left:304px;top:766px;width:99px;height:22px;text-align:center;z-index:39;"><span style="color:#000000;font-family:Arial;font-size:19px;"><strong id="pfu5_a1" class="analog">9.99 МПа</strong></span></div>
<div id="alarm2" class="rlamp_UnCertain" style="position:absolute;left:106px;top:766px;width:99px;height:22px;text-align:center;z-index:40;"><span style="color:#000000;font-family:Arial;font-size:19px;"><strong id="pfu5_a2" class="analog">9.99 МПа</strong></span></div>
<!-- Картинки -->
<div id="pfu5_d43" class="meh_off" style="position:absolute;left:555px;top:609px;width:17px;height:17px;z-index:42;"><img src="/ASUTP/img/cshi_pfu5/img0001.png" alt=""></div>
<div id="pfu5_d44" class="meh_off" style="position:absolute;left:638px;top:761px;width:17px;height:17px;z-index:43;"><img src="/ASUTP/img/cshi_pfu5/img0001.png" alt=""></div>
<div id="pfu5_d45" class="meh_off" style="position:absolute;left:531px;top:709px;width:88px;height:17px;z-index:44;"><img src="/ASUTP/img/cshi_pfu5/img0003.png" alt=""></div>
<div id="pfu5_md11" class="meh_off" style="position:absolute;left:300px;top:89px;width:106px;height:73px;z-index:48;"><img src="/ASUTP/img/cshi_pfu5/img0007.png" alt=""></div>
<div id="pfu5_md43" class="meh_off" style="position:absolute;left:446px;top:89px;width:106px;height:73px;z-index:49;"><img src="/ASUTP/img/cshi_pfu5/img0008.png" alt=""></div>
<div id="pfu5_md75" class="meh_off" style="position:absolute;left:651px;top:98px;width:89px;height:73px;z-index:50;"><img src="/ASUTP/img/cshi_pfu5/pit3.png" alt=""></div>
<div id="pfu5_md107" class="meh_off" style="position:absolute;left:812px;top:99px;width:89px;height:73px;z-index:51;"><img src="/ASUTP/img/cshi_pfu5/pit3.png" alt=""></div>
<div id="pfu5_md139" class="meh_off" style="position:absolute;left:48px;top:177px;width:134px;height:29px;z-index:65;"><img src="/ASUTP/img/cshi_pfu5/shliker.png" alt=""></div>
<div id="pfu5_d39" class="meh_off" style="position:absolute;left:491px;top:410px;width:113px;height:101px;z-index:62;"><img src="/ASUTP/img/cshi_pfu5/img0009.png" alt=""></div>
<div id="pfu5_md3" class="meh_off" style="position:absolute;left:388px;top:178px;width:19px;height:15px;z-index:53;"><img src="/ASUTP/img/cshi_pfu5/arrow.png" alt=""></div>
<div id="pfu5_md35" class="meh_off" style="position:absolute;left:447px;top:177px;width:19px;height:15px;z-index:54;"><img src="/ASUTP/img/cshi_pfu5/arrow.png" alt=""></div>
<div id="pfu5_md67" class="meh_off" style="position:absolute;left:654px;top:177px;width:19px;height:15px;z-index:55;"><img src="/ASUTP/img/cshi_pfu5/arrow.png" alt=""></div>
<div id="pfu5_md99" class="meh_off" style="position:absolute;left:814px;top:178px;width:19px;height:15px;z-index:56;"><img src="/ASUTP/img/cshi_pfu5/arrow.png" alt=""></div>
<div id="pfu5_md131" class="meh_off" style="position:absolute;left:146px;top:220px;width:19px;height:15px;z-index:52;"><img src="/ASUTP/img/cshi_pfu5/arrow.png" alt=""></div>
<div id="pfu5_md4" class="meh_off" style="position:absolute;left:335px;top:362px;width:19px;height:15px;z-index:58;"><img src="/ASUTP/img/cshi_pfu5/arrow.png" alt=""></div>
<div id="pfu5_md36" class="meh_off" style="position:absolute;left:484px;top:361px;width:19px;height:15px;z-index:59;"><img src="/ASUTP/img/cshi_pfu5/arrow.png" alt=""></div>
<div id="pfu5_md68" class="meh_off" style="position:absolute;left:688px;top:359px;width:19px;height:15px;z-index:60;"><img src="/ASUTP/img/cshi_pfu5/arrow.png" alt=""></div>
<div id="pfu5_md100" class="meh_off" style="position:absolute;left:837px;top:360px;width:19px;height:15px;z-index:61;"><img src="/ASUTP/img/cshi_pfu5/arrow.png" alt=""></div>
<div id="pfu5_md132" class="meh_off" style="position:absolute;left:151px;top:402px;width:19px;height:15px;z-index:57;"><img src="/ASUTP/img/cshi_pfu5/arrow.png" alt=""></div>
<div id="pfu5_d47" class="meh_off" style="position:absolute;left:87px;top:532px;width:69px;height:59px;z-index:63;"><img src="/ASUTP/img/cshi_pfu5/img0010.png" alt=""></div>
<div id="pfu5_d40" class="meh_off" style="position:absolute;left:491px;top:506px;width:85px;height:35px;z-index:64;"><img src="/ASUTP/img/cshi_pfu5/dnishe.png" alt=""></div>
<div id="pfu5_md9" class="meh_off" style="position:absolute;left:309px;top:342px;width:46px;height:18px;z-index:67;"><img src="/ASUTP/img/cshi_pfu5/zatvor2.png" alt=""></div>
<div id="pfu5_md41" class="meh_off" style="position:absolute;left:455px;top:340px;width:46px;height:18px;z-index:68;"><img src="/ASUTP/img/cshi_pfu5/zatvor2.png" alt=""></div>
<div id="pfu5_md73" class="meh_off" style="position:absolute;left:687px;top:339px;width:46px;height:18px;z-index:70;"><img src="/ASUTP/img/cshi_pfu5/zatvor1.png" alt=""></div>
<div id="pfu5_md105" class="meh_off" style="position:absolute;left:809px;top:340px;width:46px;height:18px;z-index:69;"><img src="/ASUTP/img/cshi_pfu5/zatvor2.png" alt=""></div>
<div id="pfu5_md137" class="meh_off" style="position:absolute;left:153px;top:382px;width:46px;height:18px;z-index:66;"><img src="/ASUTP/img/cshi_pfu5/zatvor1.png" alt=""></div>
<!-- New -->
<div id="pfu5_mixer_state" class="mixer_UnCertain" style="position:absolute;left:934px;top:324px;width:251px;height:19px;text-align:center;z-index:13;"><span style="color:#000000;font-family:Arial;font-size:17px;"><strong id="pfu5_mixer_state_text">-</strong></span></div>
<div style="position:absolute;left:1015px;top:97px;width:79px;height:16px;text-align:center;z-index:1;"><span style="color:#000000;font-family:Arial;font-size:13px;"><strong id="pfu5_r11" class="analog">-</strong></span></div>
<div style="position:absolute;left:1105px;top:97px;width:79px;height:16px;text-align:center;z-index:2;"><span style="color:#000000;font-family:Arial;font-size:13px;"><strong id="pfu5_r12" class="analog">-</strong></span></div>
<div style="position:absolute;left:1015px;top:117px;width:79px;height:16px;text-align:center;z-index:3;"><span style="color:#000000;font-family:Arial;font-size:13px;"><strong id="pfu5_r21" class="analog">-</strong></span></div>
<div style="position:absolute;left:1105px;top:117px;width:79px;height:16px;text-align:center;z-index:4;"><span style="color:#000000;font-family:Arial;font-size:13px;"><strong id="pfu5_r22" class="analog">-</strong></span></div>
<div style="position:absolute;left:1015px;top:138px;width:79px;height:16px;text-align:center;z-index:5;"><span style="color:#000000;font-family:Arial;font-size:13px;"><strong id="pfu5_r31" class="analog">-</strong></span></div>
<div style="position:absolute;left:1105px;top:138px;width:79px;height:16px;text-align:center;z-index:6;"><span style="color:#000000;font-family:Arial;font-size:13px;"><strong id="pfu5_r32" class="analog">-</strong></span></div>
<div style="position:absolute;left:1015px;top:159px;width:79px;height:16px;text-align:center;z-index:7;"><span style="color:#000000;font-family:Arial;font-size:13px;"><strong id="pfu5_r41" class="analog">-</strong></span></div>
<div style="position:absolute;left:1105px;top:159px;width:79px;height:16px;text-align:center;z-index:8;"><span style="color:#000000;font-family:Arial;font-size:13px;"><strong id="pfu5_r42" class="analog">-</strong></span></div>
<div style="position:absolute;left:1015px;top:180px;width:79px;height:16px;text-align:center;z-index:9;"><span style="color:#000000;font-family:Arial;font-size:13px;"><strong id="pfu5_r51" class="analog">-</strong></span></div>
<div style="position:absolute;left:1105px;top:180px;width:79px;height:16px;text-align:center;z-index:10;"><span style="color:#000000;font-family:Arial;font-size:13px;"><strong id="pfu5_r52" class="analog">-</strong></span></div>
<div style="position:absolute;left:1015px;top:222px;width:79px;height:16px;text-align:center;z-index:11;"><span style="color:#000000;font-family:Arial;font-size:13px;"><strong id="sum">-</strong></span></div>
<div style="position:absolute;left:1105px;top:201px;width:79px;height:16px;text-align:center;z-index:12;"><span style="color:#000000;font-family:Arial;font-size:13px;"><strong id="pfu5_r62" class="analog">-</strong></span></div>
<div style="position:absolute;left:1086px;top:351px;width:98px;height:22px;text-align:center;z-index:14;"><span style="color:#000000;font-family:Arial;font-size:19px;"><strong id="pfu5_batch_number" class="analog">-</strong></span></div>
<div style="position:absolute;left:1086px;top:380px;width:98px;height:22px;text-align:center;z-index:15;"><span style="color:#000000;font-family:Arial;font-size:19px;"><strong id="pfu5_mixer_timer" class="analog">-</strong></span></div>
<div id="pfu5_do20" class="ylamp_UnCertain" style="position:absolute;left:931px;top:466px;width:256px;height:19px;text-align:center;z-index:16;"><span style="color:#000000;font-family:Arial;font-size:17px;"><strong>Последний цикл</strong></span></div>
<div id="pfu5_di52" class="rlamp_UnCertain" style="position:absolute;left:931px;top:490px;width:256px;height:19px;text-align:center;z-index:16;"><span style="color:#000000;font-family:Arial;font-size:17px;"><strong>Аварийный останов</strong></span></div>
<div id="pfu5_do19" class="glamp_UnCertain" style="position:absolute;left:931px;top:442px;width:128px;height:19px;text-align:center;z-index:17;"><span style="color:#000000;font-family:Arial;font-size:17px;"><strong>Работа</strong></span></div>
<div id="pfu5_do21" class="rlamp_UnCertain" style="position:absolute;left:1060px;top:442px;width:127px;height:19px;text-align:center;z-index:18;"><span style="color:#000000;font-family:Arial;font-size:17px;"><strong>Авария</strong></span></div>